# Generated by Django 5.1.3 on 2024-11-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_rename_category_product_category_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
