# Generated by Django 5.1.3 on 2024-11-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_product_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
