# Generated by Django 5.1.3 on 2024-11-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_product_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
